<img src="img/nihontizu.png" usemap="#ImageMap">
<map name="ImageMap">
  <area shape="rect" coords="593,1,814,162" href="{{action('PostController@getlists',['parame' => '北海道'])}}" alt="北海道" />
  <area shape="rect" coords="592,185,751,233" href="{{action('PostController@getlists',['parame' => '青森県'])}}" alt="青森" />
  <area shape="rect" coords="594,234,669,292" href="{{action('PostController@getlists',['parame' => '秋田県'])}}" alt="秋田" />
  <area shape="rect" coords="674,238,754,289" href="{{action('PostController@getlists',['parame' => '岩手県'])}}" alt="岩手" />
  <area shape="rect" coords="592,293,677,339" href="{{action('PostController@getlists',['parame' => '山形県'])}}" alt="山形" />
  <area shape="rect" coords="673,294,751,356" href="{{action('PostController@getlists',['parame' => '宮城県'])}}" alt="宮城" />
  <area shape="rect" coords="623,355,749,410" href="{{action('PostController@getlists',['parame' => '福島県'])}}" alt="福島" />
  <area shape="rect" coords="594,413,655,471" href="{{action('PostController@getlists',['parame' => '群馬県'])}}" alt="群馬" />
  <area shape="rect" coords="655,416,712,471" href="{{action('PostController@getlists',['parame' => '栃木県'])}}" alt="栃木" />
  <area shape="rect" coords="713,417,751,492" href="{{action('PostController@getlists',['parame' => '茨木県'])}}" alt="茨城" />
  <area shape="rect" coords="713,493,752,632" href="{{action('PostController@getlists',['parame' => '千葉県'])}}" alt="千葉" />
  <area shape="rect" coords="593,475,712,521" href="{{action('PostController@getlists',['parame' => '埼玉県'])}}" alt="埼玉" />
  <area shape="rect" coords="624,528,707,570" href="{{action('PostController@getlists',['parame' => '東京都'])}}" alt="東京" />
  <area shape="rect" coords="612,579,692,638" href="{{action('PostController@getlists',['parame' => '神奈川県'])}}" alt="神奈川" />
  <area shape="rect" coords="542,356,624,413" href="{{action('PostController@getlists',['parame' => '新潟県'])}}" alt="新潟" />
  <area shape="rect" coords="480,352,543,415" href="{{action('PostController@getlists',['parame' => '富山県'])}}" alt="富山" />
  <area shape="rect" coords="445,336,481,413" href="{{action('PostController@getlists',['parame' => '石川県'])}}" alt="石川" />
  <area shape="rect" coords="403,416,483,471" href="{{action('PostController@getlists',['parame' => '福井県'])}}" alt="福井" />
  <area shape="rect" coords="523,414,593,521" href="{{action('PostController@getlists',['parame' => '長野県'])}}" alt="長野" />
  <area shape="rect" coords="485,417,523,570" href="{{action('PostController@getlists',['parame' => '岐阜県'])}}" alt="岐阜" />
  <area shape="rect" coords="564,527,623,569" href="{{action('PostController@getlists',['parame' => '山梨県'])}}" alt="山梨" />
  <area shape="rect" coords="541,574,592,631" href="{{action('PostController@getlists',['parame' => '静岡県'])}}" alt="静岡" />
  <area shape="rect" coords="483,575,544,632" href="{{action('PostController@getlists',['parame' => '愛知県'])}}" alt="愛知" />
  <area shape="rect" coords="444,477,482,534" href="{{action('PostController@getlists',['parame' => '滋賀県'])}}" alt="滋賀" />
  <area shape="rect" coords="364,474,443,531" href="{{action('PostController@getlists',['parame' => '京都府'])}}" alt="京都" />
  <area shape="rect" coords="445,533,483,675" href="{{action('PostController@getlists',['parame' => '三重県'])}}" alt="三重" />
  <area shape="rect" coords="401,535,443,634" href="{{action('PostController@getlists',['parame' => '奈良県'])}}" alt="奈良" />
  <area shape="rect" coords="364,535,402,605" href="{{action('PostController@getlists',['parame' => '大阪府'])}}" alt="大阪" />
  <area shape="rect" coords="362,630,442,674" href="{{action('PostController@getlists',['parame' => '和歌山県'])}}" alt="和歌山" />
  <area shape="rect" coords="323,433,365,553" href="{{action('PostController@getlists',['parame' => '兵庫県'])}}" alt="兵庫" />
  <area shape="rect" coords="285,437,321,494" href="{{action('PostController@getlists',['parame' => '鳥取県'])}}" alt="鳥取" />
  <area shape="rect" coords="287,497,319,551" href="{{action('PostController@getlists',['parame' => '岡山県'])}}" alt="岡山" />
  <area shape="rect" coords="243,433,284,493" href="{{action('PostController@getlists',['parame' => '島根県'])}}" alt="島根" />
  <area shape="rect" coords="244,495,283,547" href="{{action('PostController@getlists',['parame' => '広島県'])}}" alt="広島" />
  <area shape="rect" coords="204,435,242,550" href="{{action('PostController@getlists',['parame' => '山口県'])}}" alt="山口" />
  <area shape="rect" coords="273,570,344,627" href="{{action('PostController@getlists',['parame' => '香川県'])}}" alt="香川" />
  <area shape="rect" coords="204,578,273,621" href="{{action('PostController@getlists',['parame' => '愛媛県'])}}" alt="愛媛" />
  <area shape="rect" coords="272,627,343,673" href="{{action('PostController@getlists',['parame' => '徳島県'])}}" alt="徳島" />
  <area shape="rect" coords="203,626,274,673" href="{{action('PostController@getlists',['parame' => '高知県'])}}" alt="高知" />
  <area shape="rect" coords="146,476,180,542" href="{{action('PostController@getlists',['parame' => '大分県'])}}" alt="大分" />
  <area shape="rect" coords="143,545,181,611" href="{{action('PostController@getlists',['parame' => '宮崎県'])}}" alt="宮崎" />
  <area shape="rect" coords="83,437,142,526" href="{{action('PostController@getlists',['parame' => '福岡県'])}}" alt="福岡" />
  <area shape="rect" coords="84,527,143,611" href="{{action('PostController@getlists',['parame' => '熊本県'])}}" alt="熊本" />
  <area shape="rect" coords="83,615,183,674" href="{{action('PostController@getlists',['parame' => '鹿児島県'])}}" alt="鹿児島" />
  <area shape="rect" coords="44,436,82,521" href="{{action('PostController@getlists',['parame' => '佐賀県'])}}" alt="佐賀" />
  <area shape="rect" coords="3,437,41,523" href="{{action('PostController@getlists',['parame' => '長崎県'])}}" alt="長崎" />
  <area shape="rect" coords="78,692,125,755" href="{{action('PostController@getlists',['parame' => '沖縄県'])}}" alt="沖縄" />
</map>
